docs: Changed remaining links to sources to API docs
influxdata/influxdb-client-go pull request #222
Opened 2020-12-22 12:38 UTC by vlastahajek

Change links leading to sources to go to API docs

## Checklist

- [X] CHANGELOG.md updated
- [X] Rebased/mergeable
- [X] Tests pass
- [X] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

2020-12-22 16:33 UTC, sranka requested changes
Look good, but I think that we should not reference an exact version (v2.2.0) in markdown files, but rather the latest version of v2.

2020-12-22 16:33 UTC, sranka commented on README.md
> +        - Both [asynchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#WriteAPI) or [synchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.
```suggestion
        - Both [asynchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteAPI) or [synchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteAPIBlocking) ways
```

2020-12-22 16:33 UTC, sranka commented on README.md
> + - [Management APIs](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api?tab=doc#pkg-examples)
```suggestion
 - [Management APIs](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api?tab=doc#pkg-examples) 
```

2020-12-22 16:33 UTC, sranka commented on README.md
> +Query client offers retrieving of query results to a parsed representation in a [QueryTableResult](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#QueryTableResult) or to a
```suggestion
Query client offers retrieving of query results to a parsed representation in a [QueryTableResult](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#QueryTableResult) or to a raw string. 
```

2020-12-22 16:33 UTC, sranka commented on README.md
> +  | [WriteAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#WriteAPI) (also [WriteAPIBlocking](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#W
```suggestion
  | [WriteAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteAPI) (also [WriteAPIBlocking](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteAPIBlocking))| [/api/v2/write](https://docs.influxdata.com/influxdb/latest/tools/api/#api-v2-write-http-endpoint) | Write data to InfluxDB 1.8.0+ using the InfluxDB 2.0 API |
```

2020-12-22 16:33 UTC, sranka commented on README.md
> +  | [QueryAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#QueryAPI) | [/api/v2/query](https://docs.influxdata.com/influxdb/latest/tools/api/#api-v2-query-http-endpoint)
```suggestion
  | [QueryAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#QueryAPI) | [/api/v2/query](https://docs.influxdata.com/influxdb/latest/tools/api/#api-v2-query-http-endpoint) | Query data in InfluxDB 1.8.0+ using the InfluxDB 2.0 API and [Flux](https://docs.influxdata.com/flux/latest/) endpoint should be enabled by the [`flux-enabled` option](https://docs.influxdata.com/influxdb/latest/administration/config/#flux-enabled-false)
```

2020-12-22 16:33 UTC, sranka commented on README.md
>          - [Data Point](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/write#Point)
```suggestion
        - [Data Point](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api/write#Point)
```

2020-12-23 10:40 UTC, vlastahajek commented
@sranka, thanks for the suggestions. I wanted to have links without a version, but it didn't work for me, for some reason. 
But it is OK now.

2020-12-23 10:45 UTC, ivankudibal approved these changes

2020-12-23 10:48 UTC, vlastahajek commented on README.md
>          - [Data Point](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/write#Point)
Done

2020-12-23 10:48 UTC, vlastahajek commented on README.md
> +        - Both [asynchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#WriteAPI) or [synchronous](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.
Done

2020-12-23 10:49 UTC, vlastahajek commented on README.md
> + - [Management APIs](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api?tab=doc#pkg-examples)
Done

2020-12-23 10:49 UTC, vlastahajek commented on README.md
> +Query client offers retrieving of query results to a parsed representation in a [QueryTableResult](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#QueryTableResult) or to a
Done

2020-12-23 10:49 UTC, vlastahajek commented on README.md
> +  | [WriteAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#WriteAPI) (also [WriteAPIBlocking](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#W
Done

2020-12-23 10:49 UTC, vlastahajek commented on README.md
> +  | [QueryAPI](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api#QueryAPI) | [/api/v2/query](https://docs.influxdata.com/influxdb/latest/tools/api/#api-v2-query-http-endpoint)
Done

2020-12-23 10:51 UTC, merged