feat: allow Doer interface for http.Service
influxdata/influxdb-client-go pull request #256
Opened 2021-05-14 17:36 UTC by lesam

Closes #255

## Proposed Changes

See issue #255

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] Tests pass
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-05-14 17:53 UTC, lesam commented
I need this to support this PR: https://github.com/influxdata/flux/pull/3718

2021-05-17 11:54 UTC, vlastahajek requested changes
Thanks for the PR!
In general, supporting Doer interface is a good enhancement 👍 

Implementation can be less complex by adding `SetHTTPDoer` and `HTTPDoer()` do api/http/Options.

2021-05-17 13:17 UTC, lesam commented
I'm not sure that would be less complex.

We do need other methods (e.g. CloseIdleConnections) elsewhere, so we would have to error or panic when calling options.HTTPClient() if the client was not set up correctly - this seems worse than adding a constructor on Service.

2021-05-17 14:16 UTC, vlastahajek requested changes
Thanks for the update. Just a couple of changes to-do yet.

2021-05-17 14:16 UTC, vlastahajek commented on CHANGELOG.md
> +[#256](https://github.com/influxdata/influxdb-client-go/pull/256) struct http.Service can be created with a 'Doer' interface
```suggestion
[#256](https://github.com/influxdata/influxdb-client-go/pull/256) Allowing 'Doer' interface  for HTTP requests
```

2021-05-17 14:16 UTC, vlastahajek commented on api/http/options.go
> +	return o
```suggestion
	if d != nil {
		o.doer = d
		o.ownClient = false
	}
	return o
```

2021-05-17 14:16 UTC, vlastahajek commented on api/http/options.go
> +
```suggestion
// HTTPDoer returns actual Doer if set, or http.Client
```

2021-05-17 17:08 UTC, vlastahajek approved these changes

2021-05-18 12:06 UTC, merged