Write retry fixes
influxdata/influxdb-client-go pull request #332
Opened 2022-06-03 02:42 UTC by seth-hunter

Fixes:
- Logic error in management of retry buffer that leads to write retries ceasing if server connection is lost for longer than MaxRetryTime
- Creation of new batches not obeying MaxRetryInterval

2022-06-10 11:47 UTC, vlastahajek requested changes
Thanks for finding the issue and the fix!

Just a few minor things:
 1. Fix tests, please. You can use this patch [PR332TestFix.zip](https://github.com/influxdata/influxdb-client-go/files/8878499/PR332TestFix.zip) via `git apply`
  2. Change commit messages to be semantic. 
  3. Small change in the error message to be consistent with other messages

2022-06-11 19:01 UTC, seth-hunter commented on internal/write/service.go
> +					log.Warn("Write proc: oldest batch in retry queue expired, discarding...")
These should be resolved in the PR's updated branch.

2022-06-11 19:09 UTC, seth-hunter commented
@vlastahajek: thank you for the guidance. Updated branch should address your comments.  In further testing I believe I uncovered an additional related issue and the fix for that has been included in the revised branch.  Requesting your review on that.  Corresponding internal/write tests updated and pass, but I missed an api/write test failure that I will need to digest and think about later (or help appreciated).

2022-06-11 20:46 UTC, seth-hunter commented
@vlastahajek: thank you for the review and suggestions. Updated branch should address your comments and also fix an additional closely-related issue I found during further testing. Requesting your review on that, as it may be a little more subjective from a design perspective.

2022-06-20 10:36 UTC, vlastahajek approved these changes

2022-06-20 10:36 UTC, merged

2022-06-20 10:36 UTC, vlastahajek commented
Thanks!